festival_representation:
    resource: "@FestivalRepresentationBundle/Resources/config/routing.yml"
    prefix:   /gestionRepresentation

festival_hebergement:
    resource: "@FestivalHebergementBundle/Resources/config/routing.yml"
    prefix:   /gestionHebergement

festival_lieu:
    resource: "@FestivalLieuBundle/Resources/config/routing.yml"
    prefix:   /gestionLieu

festival_etablissement:
    resource: "@FestivalEtablissementBundle/Resources/config/routing.yml"
    prefix:   /gestionEtablissement

festival_groupe:
    resource: "@FestivalGroupeBundle/Resources/config/routing.yml"
    prefix:   /gestionGroupe

festival_core:
    resource: "@FestivalCoreBundle/Resources/config/routing.yml"
    prefix:   /