festival_etablissement:
    resource: "@FestivalEtablissementBundle/Resources/config/routing.yml"
    prefix:   /gestionEtablissement

festival_groupe:
    resource: "@FestivalGroupeBundle/Resources/config/routing.yml"
    prefix:   /gestionGroupe

festival_core:
    resource: "@FestivalCoreBundle/Resources/config/routing.yml"
    prefix:   /