<?php

namespace Festival\RepresentationBundle\Repository;

/**
 * RepresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentationRepository extends \Doctrine\ORM\EntityRepository
{
}
