Festival\RepresentationBundle\Entity\Representation:
    type: entity
    table: null
    repositoryClass: Festival\RepresentationBundle\Repository\RepresentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbPlacesDispo:
            type: integer
        date:
            type: date
    lifecycleCallbacks: {  }
