<?php

namespace Festival\LieuBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLieu()
    {
	return $this
            ->createQueryBuilder('l')
            ->getQuery()
            ->getResult()
	;
    }

    public function getOneById($id)
    {
	$qb = $this->createQueryBuilder('l');

	$qb
            ->where('l.id = :id')
            ->setParameter('id', $id)
	;

	return $qb
            ->getQuery()
            ->getResult()
	;
    }
    
}