festival_etablissement_listeetablissements:
    path:     /etablissement
    defaults: { _controller: FestivalEtablissementBundle:Etablissement:listeEtablissements }
    
festival_etablissement_etablissement:
    path:     /etablissement/{id}
    defaults: { _controller: FestivalEtablissementBundle:Etablissement:unEtablissement }
    requirements:
        id: \d+
        
festival_etablissement_ajoutetablissement:
    path:     /etablissement/ajout
    defaults: { _controller: FestivalEtablissementBundle:Etablissement:ajouterEtablissement }
    
festival_etablissement_modifieretablissement:
    path:     /etablissement/modifier/{id}
    defaults: { _controller: FestivalEtablissementBundle:Etablissement:modifierEtablissement }
    requirements:
        id: \d+
        
festival_etablissement_effaceretablissement:
    path:     /etablissement/effacer/{id}
    defaults: { _controller: FestivalEtablissementBundle:Etablissement:effacerEtablissement }
    requirements:
        id: \d+


    
festival_etablissement_listechambres:
    path:     /chambre
    defaults: { _controller: FestivalEtablissementBundle:Chambre:listeChambres }

festival_etablissement_chambre:
    path:     /chambre/{id}
    defaults: { _controller: FestivalEtablissementBundle:Chambre:uneChambre }
    requirements:
        id: \d+
        
festival_etablissement_ajoutchambre:
    path:     /chambre/ajout
    defaults: { _controller: FestivalEtablissementBundle:Chambre:ajouterChambre }
    
festival_etablissement_modifierchambre:
    path:     /chambre/modifier/{id}
    defaults: { _controller: FestivalEtablissementBundle:Chambre:modifierChambre }
    requirements:
        id: \d+
        
festival_etablissement_effacerchambre:
    path:     /chambre/effacer/{id}
    defaults: { _controller: FestivalEtablissementBundle:Chambre:effacerChambre }
    requirements:
        id: \d+